name: DartTemplateMinimal
version: 0.0.1
author: tom.nguyen@xxx.com
description: Some descript
homepage: https://github.com/tomng92/DartTemplateMinimal
documentation: https://github.com/tomng92/DartTemplateMinimal/README.md
dependencies:
  unittest: any
  browser: any
